# Project information
site_name: 'IT Docs'
site_description: 'IT Docs - Notes from my adventures in IT'
site_author: 'Jean-Francois Desrochers'
site_url: 'https://jfdesrochers.github.io/itdocs'

# Project structure

docs_dir: 'docs'
site_dir: 'site'

pages:
- Welcome: 'index.md'
- Linux Sys Admin:
    - "Creating SSH keys and aliases": 'linux-sys-admin/creating-ssh-keys.md'
- Infrastructure
    - "How to replace/upgrade a drive in a HP MSA P2000": 'infrastructure/replace-hdd-p2000.md'

# Copyright
copyright: 'Copyright &copy; 2018 Jean-Francois Desrochers'

# Documentation and theme
theme: 'material'

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/jfdesrochers/itdocs'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)